/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package checkout;

import database.account;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.*;
import database.*;

/**
 *
 * @author Taki
 */
public class CheckoutView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CheckoutView.class.getName());

    /* ATRIBUT */
    account cust;
    Transaksi transaksi;
    CheckoutService CS;
    dashboard dash;
    
    /* METHOD */
    // KONSTRUKTOR
    public CheckoutView(account cust, Transaksi transaksi) {
        // Kamus
        this.cust = cust;
        this.transaksi = transaksi;
        
        // Algoritma        
        initComponents();
        
        AlamatPengiriman.setText(cust.getAlamat());
        
        //Tabel_produkDipesan.??? ini ganti yang lain yang bisa 
        // discroll ke bawah menampilkan semua produk yang dipesan
        // urut dari kiri Nama Produk, Harga Satuan, Jumlah, Subtotal
        
        TotalHarga.setText(Double.toString(transaksi.getTotalBelanja()));
        
        showDataTransaction(transaksi.getItems());
    }

    private CheckoutView() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    
    // GETTER
    // SETTER
    // METHOD LAIN
    public void showDataTransaction(List<CartItem> products) {
        DefaultTableModel model = (DefaultTableModel) Tabel_produkDipesan.getModel();
        model.setRowCount(0); // Clear existing rows

        for (CartItem produk : products) {
            Object[] row = {
                produk.getProduk().getNamaProduk(),
                produk.getProduk().getHarga(),
                produk.getQuantity(),
                produk.getSubtotal() // asumsi subtotal sudah dihitung di CartItem
            };
            model.addRow(row);
        }
    }

    public void showCheckoutStatus(boolean status) {
        String message = status ? "Checkout berhasil!" : "Checkout gagal. Saldo tidak cukup.";
        String title = status ? "Berhasil" : "Gagal";
        
        int option = JOptionPane.showOptionDialog(
            null,
            message,
            title,
            JOptionPane.DEFAULT_OPTION,
            status ? JOptionPane.INFORMATION_MESSAGE : JOptionPane.ERROR_MESSAGE,
            null,
            new String[]{"Kembali ke Dashboard"},
            "Kembali ke Dashboard"
        );

        // Kalau user klik tombol
        if (option == 0) {
            dash = new dashboard();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainScrollPanel = new javax.swing.JScrollPane();
        MainPanel = new javax.swing.JPanel();
        Panel_AlamatPengiriman = new javax.swing.JPanel();
        Label_AlamatPengiriman = new javax.swing.JLabel();
        AlamatPengiriman = new javax.swing.JLabel();
        Tabel_produkDipesan = new javax.swing.JTable();
        Panel_TotalBill = new javax.swing.JPanel();
        Label_Total = new javax.swing.JLabel();
        Button_BuatPesanan = new javax.swing.JButton();
        TotalHarga = new javax.swing.JLabel();
        Panel_Heading = new javax.swing.JPanel();
        Label_Checkout = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainPanel.setPreferredSize(new java.awt.Dimension(400, 406));

        Panel_AlamatPengiriman.setBackground(new java.awt.Color(186, 230, 255));
        Panel_AlamatPengiriman.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Panel_AlamatPengiriman.setToolTipText("");

        Label_AlamatPengiriman.setText("Alamat Pengiriman");
        Label_AlamatPengiriman.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                Label_AlamatPengirimanAncestorMoved(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        AlamatPengiriman.setText("alamat");
        AlamatPengiriman.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                AlamatPengirimanAncestorMoved(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout Panel_AlamatPengirimanLayout = new javax.swing.GroupLayout(Panel_AlamatPengiriman);
        Panel_AlamatPengiriman.setLayout(Panel_AlamatPengirimanLayout);
        Panel_AlamatPengirimanLayout.setHorizontalGroup(
            Panel_AlamatPengirimanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_AlamatPengirimanLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(Panel_AlamatPengirimanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_AlamatPengiriman)
                    .addComponent(AlamatPengiriman, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        Panel_AlamatPengirimanLayout.setVerticalGroup(
            Panel_AlamatPengirimanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_AlamatPengirimanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_AlamatPengiriman)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AlamatPengiriman)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        Tabel_produkDipesan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Produk", "Harga Satuan", "Jumlah", "Subtotal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabel_produkDipesan.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Tabel_produkDipesan.setName(""); // NOI18N
        Tabel_produkDipesan.setShowGrid(true);
        Tabel_produkDipesan.setSurrendersFocusOnKeystroke(true);
        Tabel_produkDipesan.getTableHeader().setReorderingAllowed(false);
        Tabel_produkDipesan.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                Tabel_produkDipesanPropertyChange(evt);
            }
        });

        Panel_TotalBill.setBackground(new java.awt.Color(204, 204, 204));

        Label_Total.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Label_Total.setText("Total :");

        Button_BuatPesanan.setBackground(new java.awt.Color(130, 207, 255));
        Button_BuatPesanan.setText("Buat Pesanan");
        Button_BuatPesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_BuatPesananActionPerformed(evt);
            }
        });

        TotalHarga.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        TotalHarga.setText("totalHarga");

        javax.swing.GroupLayout Panel_TotalBillLayout = new javax.swing.GroupLayout(Panel_TotalBill);
        Panel_TotalBill.setLayout(Panel_TotalBillLayout);
        Panel_TotalBillLayout.setHorizontalGroup(
            Panel_TotalBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_TotalBillLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_TotalBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Panel_TotalBillLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Button_BuatPesanan))
                    .addGroup(Panel_TotalBillLayout.createSequentialGroup()
                        .addComponent(Label_Total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(104, 104, 104)
                        .addComponent(TotalHarga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(53, 53, 53))
        );
        Panel_TotalBillLayout.setVerticalGroup(
            Panel_TotalBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_TotalBillLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(Panel_TotalBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_Total)
                    .addComponent(TotalHarga))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button_BuatPesanan)
                .addContainerGap())
        );

        Panel_Heading.setBackground(new java.awt.Color(0, 83, 154));
        Panel_Heading.setToolTipText("");

        Label_Checkout.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        Label_Checkout.setForeground(new java.awt.Color(255, 255, 255));
        Label_Checkout.setText("Checkout");

        javax.swing.GroupLayout Panel_HeadingLayout = new javax.swing.GroupLayout(Panel_Heading);
        Panel_Heading.setLayout(Panel_HeadingLayout);
        Panel_HeadingLayout.setHorizontalGroup(
            Panel_HeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_HeadingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_Checkout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel_HeadingLayout.setVerticalGroup(
            Panel_HeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_HeadingLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(Label_Checkout)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_Heading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(Panel_TotalBill, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Panel_AlamatPengiriman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Tabel_produkDipesan, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addComponent(Panel_Heading, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel_AlamatPengiriman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Tabel_produkDipesan, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Panel_TotalBill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        MainScrollPanel.setViewportView(MainPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainScrollPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Label_AlamatPengirimanAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_Label_AlamatPengirimanAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_Label_AlamatPengirimanAncestorMoved

    private void AlamatPengirimanAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_AlamatPengirimanAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_AlamatPengirimanAncestorMoved

    private void Tabel_produkDipesanPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_Tabel_produkDipesanPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_Tabel_produkDipesanPropertyChange

    private void Button_BuatPesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_BuatPesananActionPerformed
        CS.pay();
    }//GEN-LAST:event_Button_BuatPesananActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CheckoutView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AlamatPengiriman;
    private javax.swing.JButton Button_BuatPesanan;
    private javax.swing.JLabel Label_AlamatPengiriman;
    private javax.swing.JLabel Label_Checkout;
    private javax.swing.JLabel Label_Total;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JScrollPane MainScrollPanel;
    private javax.swing.JPanel Panel_AlamatPengiriman;
    private javax.swing.JPanel Panel_Heading;
    private javax.swing.JPanel Panel_TotalBill;
    private javax.swing.JTable Tabel_produkDipesan;
    private javax.swing.JLabel TotalHarga;
    // End of variables declaration//GEN-END:variables
}
