/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import javax.swing.*;
import java.awt.*;
import java.sql.*;
import java.util.ArrayList;
import java.util.List; 
import java.util.stream.Collectors;


public class dashboard2 extends javax.swing.JFrame {

    private JPanel panelProduk;
    private JScrollPane scrollPane;
    private cart keranjang;
    private service servis;
    private account user;
    private JTextField searchField;

    public dashboard2(account user) {
        this.user = user;
        this.keranjang = new cart();
        this.servis = new service();

        setTitle("Dashboard Produk");
        setSize(400, 300);
        setDefaultCloseOperation(EXIT_ON_CLOSE);

        initDashboardLayout();
        tampilkanProduk("");
    }

    private void initDashboardLayout() {
        setLayout(new BorderLayout());

        // Panel Atas
        JPanel panelAtas = new JPanel(new BorderLayout());
        panelAtas.setBackground(new Color(0, 83, 154));
        panelAtas.setPreferredSize(new Dimension(400, 50));

        JLabel saldoLabel = new JLabel("Saldo : " + user.getSaldo());
        saldoLabel.setForeground(Color.WHITE);
        saldoLabel.setFont(new Font("Segoe UI", Font.BOLD, 16));
        panelAtas.add(saldoLabel, BorderLayout.WEST);

        JPanel tombolPanel = new JPanel(new FlowLayout(FlowLayout.RIGHT));
        searchField = new JTextField(10);
        JButton btnCari = new JButton("Cari");
        JButton btnKeranjang = new JButton("Keranjang");

        btnCari.addActionListener(e -> tampilkanProduk(searchField.getText()));
        btnKeranjang.addActionListener(e -> new keranjang(user,keranjang).setVisible(true));

        tombolPanel.add(searchField);
        tombolPanel.add(btnCari);
        tombolPanel.add(btnKeranjang);

        panelAtas.add(tombolPanel, BorderLayout.EAST);
        add(panelAtas, BorderLayout.NORTH);

        // Panel Produk
        panelProduk = new JPanel();
        panelProduk.setLayout(new BoxLayout(panelProduk, BoxLayout.Y_AXIS));

        scrollPane = new JScrollPane(panelProduk);
        scrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        add(scrollPane, BorderLayout.CENTER);
    }

    private void tampilkanProduk(String keyword) {
        panelProduk.removeAll();
        List<Product> produkList = servis.loadProdukDariDatabase();

        if (!keyword.isEmpty()) {
            produkList = produkList.stream()
                .filter(p -> p.getNama().toLowerCase().contains(keyword.toLowerCase()))
                .collect(Collectors.toList());
        }

        for (Product p : produkList) {
            JPanel panel = new JPanel(new BorderLayout());
            panel.setBorder(BorderFactory.createEmptyBorder(5, 10, 5, 10));
            panel.setMaximumSize(new Dimension(Integer.MAX_VALUE, 60));
            panel.setBackground(Color.WHITE);

            JLabel nama = new JLabel(p.getNama());
            nama.setFont(new Font("Segoe UI", Font.BOLD, 18));

            JLabel harga = new JLabel("Harga : Rp. " + p.getHarga());
            harga.setFont(new Font("Segoe UI", Font.PLAIN, 14));
            harga.setHorizontalAlignment(SwingConstants.RIGHT);

            JButton btnTambah = new JButton("Tambah");
            btnTambah.setBackground(new Color(51, 102, 255));
            btnTambah.setForeground(Color.WHITE);
            btnTambah.setPreferredSize(new Dimension(80, 30));
            btnTambah.addActionListener(e -> {
                keranjang.tambahProduk(p);
                JOptionPane.showMessageDialog(this, p.getNama() + " ditambahkan ke keranjang!");
            });

            JPanel kiri = new JPanel(new BorderLayout());
            kiri.setOpaque(false);
            kiri.add(nama, BorderLayout.WEST);

            JPanel kanan = new JPanel(new FlowLayout(FlowLayout.RIGHT));
            kanan.setOpaque(false);
            kanan.add(harga);
            kanan.add(btnTambah);

            panel.add(kiri, BorderLayout.WEST);
            panel.add(kanan, BorderLayout.EAST);

            panelProduk.add(panel);
        }

        panelProduk.revalidate();
        panelProduk.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelSaldo = new javax.swing.JLabel();
        jLabelInfoSaldo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextFieldCari = new javax.swing.JTextField();
        jButtonCari = new javax.swing.JButton();
        jButtonKeranjang = new javax.swing.JButton();
        jPanelProduk = new javax.swing.JPanel();
        jButtonTambah = new javax.swing.JButton();
        jLabelNamaProduk = new javax.swing.JLabel();
        jLabelHarga = new javax.swing.JLabel();
        jLabelInfoHarga = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));

        jLabelSaldo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelSaldo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSaldo.setText("Saldo ");

        jLabelInfoSaldo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelInfoSaldo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelInfoSaldo.setText("100000");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelInfoSaldo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelSaldo)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSaldo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelInfoSaldo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 51, 255));

        jButtonCari.setText("Cari");
        jButtonCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCariActionPerformed(evt);
            }
        });

        jButtonKeranjang.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jButtonKeranjang.setText("keranjang");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonKeranjang, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextFieldCari, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCari, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonKeranjang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonCari))))
                .addContainerGap())
        );

        jPanelProduk.setBackground(new java.awt.Color(255, 255, 255));

        jButtonTambah.setBackground(new java.awt.Color(51, 102, 255));
        jButtonTambah.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jButtonTambah.setForeground(new java.awt.Color(255, 255, 255));
        jButtonTambah.setText(" tambah");

        jLabelNamaProduk.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelNamaProduk.setText("Risol Mayo");

        jLabelHarga.setText("Harga : Rp.");

        jLabelInfoHarga.setText("500");

        javax.swing.GroupLayout jPanelProdukLayout = new javax.swing.GroupLayout(jPanelProduk);
        jPanelProduk.setLayout(jPanelProdukLayout);
        jPanelProdukLayout.setHorizontalGroup(
            jPanelProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelProdukLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNamaProduk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelHarga)
                .addGap(10, 10, 10)
                .addComponent(jLabelInfoHarga)
                .addGap(18, 18, 18)
                .addComponent(jButtonTambah)
                .addContainerGap())
        );
        jPanelProdukLayout.setVerticalGroup(
            jPanelProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelProdukLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonTambah, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jLabelNamaProduk)
                    .addComponent(jLabelHarga)
                    .addComponent(jLabelInfoHarga))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelProduk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(193, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jButtonCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                account dummyUser = new account("test@mail.com", "1234", "alamat", 100000);
                new dashboard2(dummyUser).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCari;
    private javax.swing.JButton jButtonKeranjang;
    private javax.swing.JButton jButtonTambah;
    private javax.swing.JLabel jLabelHarga;
    private javax.swing.JLabel jLabelInfoHarga;
    private javax.swing.JLabel jLabelInfoSaldo;
    private javax.swing.JLabel jLabelNamaProduk;
    private javax.swing.JLabel jLabelSaldo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelProduk;
    private javax.swing.JTextField jTextFieldCari;
    // End of variables declaration//GEN-END:variables
}
