
package database;

import javax.swing.*;
import java.awt.*;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;



public class keranjang extends javax.swing.JFrame {
    private cart keranjang;
    private account user;
    private JPanel panelIsi;
    private JLabel totalLabel;
    private JLabel saldoLabel;

    public keranjang(account user, cart keranjang) {
        this.keranjang = keranjang;
        this.user = user;

        setTitle("Keranjang Belanja");
        setSize(400, 300);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        initComponents1();
        tampilkanIsiKeranjang();
    }

    private void initComponents1() {
        setLayout(new BorderLayout());

        JPanel panelAtas = new JPanel(new BorderLayout());
        panelAtas.setBackground(new Color(0, 83, 154));
        panelAtas.setPreferredSize(new Dimension(400, 40));

        saldoLabel = new JLabel("Saldo : " + user.getSaldo());
        saldoLabel.setForeground(Color.WHITE);
        saldoLabel.setFont(new Font("Segoe UI", Font.BOLD, 16));
        panelAtas.add(saldoLabel, BorderLayout.WEST);

        JPanel tombolPanel = new JPanel(new FlowLayout(FlowLayout.RIGHT));
        JButton btnHapus = new JButton("hapus");
        JButton btnKembali = new JButton("kembali");

        btnHapus.addActionListener(e -> {
            keranjang.getDaftarProduk().clear();
            tampilkanIsiKeranjang();
        });

        btnKembali.addActionListener(e -> this.dispose());

        tombolPanel.add(btnHapus);
        tombolPanel.add(btnKembali);
        panelAtas.add(tombolPanel, BorderLayout.EAST);

        add(panelAtas, BorderLayout.NORTH);

        panelIsi = new JPanel();
        panelIsi.setLayout(new BoxLayout(panelIsi, BoxLayout.Y_AXIS));
        JScrollPane scrollPane = new JScrollPane(panelIsi);
        scrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        add(scrollPane, BorderLayout.CENTER);

        JPanel panelBawah = new JPanel(new FlowLayout(FlowLayout.RIGHT));
        panelBawah.setBackground(new Color(0, 83, 154));

        totalLabel = new JLabel("Total : 0");
        totalLabel.setForeground(Color.WHITE);
        totalLabel.setFont(new Font("Segoe UI", Font.BOLD, 16));

        JButton btnCheckout = new JButton("Checkout");
        btnCheckout.addActionListener(e -> JOptionPane.showMessageDialog(this, "Proses checkout dilakukan!"));

        panelBawah.add(totalLabel);
        panelBawah.add(btnCheckout);

        add(panelBawah, BorderLayout.SOUTH);
    }

    private void tampilkanIsiKeranjang() {
        panelIsi.removeAll();
        int total = 0;

        List<Product> produkList = keranjang.getDaftarProduk();
        for (Product p : produkList) {
            JPanel panel = new JPanel(new BorderLayout());
            panel.setBackground(Color.WHITE);
            panel.setBorder(BorderFactory.createEmptyBorder(5, 10, 5, 10));

            JLabel nama = new JLabel(p.getNama());
            nama.setFont(new Font("Segoe UI", Font.BOLD, 16));

            JLabel harga = new JLabel("Rp. " + p.getHarga());
            harga.setFont(new Font("Segoe UI", Font.PLAIN, 14));

            panel.add(nama, BorderLayout.WEST);
            panel.add(harga, BorderLayout.EAST);

            panelIsi.add(panel);
            total += p.getHarga();
        }

        totalLabel.setText("Total : " + total);
        panelIsi.revalidate();
        panelIsi.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelSaldo = new javax.swing.JLabel();
        jLabelInfoSaldo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabelTotal = new javax.swing.JLabel();
        jLabelInfoTotal = new javax.swing.JLabel();
        jButtonCheckout = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabelNamaProduk = new javax.swing.JLabel();
        jLabelNamaProduk1 = new javax.swing.JLabel();
        jLabelNamaProduk2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 83, 154));
        jPanel1.setPreferredSize(new java.awt.Dimension(390, 37));

        jLabelSaldo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelSaldo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSaldo.setText("Saldo :");

        jLabelInfoSaldo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelInfoSaldo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelInfoSaldo.setText("100000");

        jButton1.setText("kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("hapus ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSaldo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelInfoSaldo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelSaldo)
                        .addComponent(jLabelInfoSaldo))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 83, 154));
        jPanel2.setPreferredSize(new java.awt.Dimension(390, 37));

        jLabelTotal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelTotal.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTotal.setText("Total :");

        jLabelInfoTotal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelInfoTotal.setForeground(new java.awt.Color(255, 255, 255));
        jLabelInfoTotal.setText("100000");

        jButtonCheckout.setText("Checkout");
        jButtonCheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCheckoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabelTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelInfoTotal)
                .addGap(18, 18, 18)
                .addComponent(jButtonCheckout)
                .addGap(15, 15, 15))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelInfoTotal)
                        .addComponent(jLabelTotal))
                    .addComponent(jButtonCheckout))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabelNamaProduk.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelNamaProduk.setText("Risol Mayo");

        jLabelNamaProduk1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNamaProduk1.setText("500");

        jLabelNamaProduk2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNamaProduk2.setText("Rp.");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabelNamaProduk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelNamaProduk2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelNamaProduk1)
                .addGap(21, 21, 21))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNamaProduk)
                    .addComponent(jLabelNamaProduk1)
                    .addComponent(jLabelNamaProduk2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonCheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCheckoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCheckoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            account dummyUser = new account();
            cart dummyCart = new cart();
            new keranjang(dummyUser, dummyCart).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonCheckout;
    private javax.swing.JLabel jLabelInfoSaldo;
    private javax.swing.JLabel jLabelInfoTotal;
    private javax.swing.JLabel jLabelNamaProduk;
    private javax.swing.JLabel jLabelNamaProduk1;
    private javax.swing.JLabel jLabelNamaProduk2;
    private javax.swing.JLabel jLabelSaldo;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
